<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tmpl"
 *
 * Auto generated by Extension Builder 2020-04-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'tmpl',
	'description' => 'Rendering template site',
	'category' => 'plugin',
	'author' => 'Dmitry Vasilev',
	'author_email' => 'dmitry@t3dev.ru',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
            'cms' => '',
            'extbase' => '',
            'fluid' => '',
            'flux' => '',
            'fluidpages' => '',
            'fluidcontent' => '',
            'vhs' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);