<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3devslider"
 *
 * Auto generated by Extension Builder 2016-06-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'T3Dev Slider',
	'description' => 'T3Dev Slider',
	'category' => 'plugin',
	'author' => 'Dmitry Vasiliev',
	'author_email' => 'dmitry@t3dev.ru',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);